### ISSUE TITLE
Pariser-Parr dictionary

### ISSUE THREAD

**Issue by RichRick1** [theochem/ModelHamiltonian#116]
1. When we build Pariser-Parr dictionary, we assume user provides connectivity matrix as ('atomx, 'atomy', 'Rxy'). Where $R_{xy}$ is a distance between atoms x and y. 

2. To compute hopping term $\beta_{xy}$ we need to compute overlap between orbitals $S_{xy}$:
$$\beta_{X Y}=1.75 S_{X Y} \frac{\alpha_X+\alpha_Y}{2}$$

**Problem**: computation of $S_{xy}$  depends, among other parameters, on type of orbitals: 
![image](https://github.com/theochem/ModelHamiltonian/assets/36164007/85393475-9596-4381-95ad-824f6c866dec)
 and 
<img width="650" alt="image" src="https://github.com/theochem/ModelHamiltonian/assets/36164007/5fc50a81-6673-4771-9440-805fc93e8e8c">

@PaulWAyers what do you think is the best way from API perspective to choose the type of overlap-computations?

**Comment by PaulWAyers** [comment]
Perhaps have an option for the overlap calculation, where the user can specify `s` or `p`; then we can indicate in the documentation what these keywords mean, specifically. 

A more advanced option would be to support passing a string (here `s` or `p`) or a function, whereby the user passes their own overlap function. That would add a lot of flexibility, since basically the any overlap function could be used. (Under the hood, the keyword arguments would just call the code with the function as specified here.)

What do you think?

**Comment by RichRick1** [comment]
What if instead of the passing a function, we let user pass the overlap matrix for directly? Such approach will provide the same flexibility, but eliminates a problem of restricting formatting for the function that user provides

**Comment by PaulWAyers** [comment]
That's a good idea. We can provide some utilities for constructing the overlap matrix and then pass it.

**Comment by RichRick1** [comment]
# Two body term

## Computing `u_onsite`

### Function name: `compute_U` in the rauk module, PariserParr.py
1. For the computation of potential on each site, if user didn't provide `u_onsite` (`u_onsite` is `None`) or `affinity_dct is None`, then function pull information about binding affinity from the Json file. It should also know (or read) `atom_dct`
2. Computation of u_onsite is done by $U_X = \alpha_X - A_X$

## Computing `gamma`
### Function name: `compute_gamma` in the rauk module, PariserParr.py
1. For the computation of $\gamma_{XY}$ if `gamma is None` we need to call `compute_U` to evaluate $U_x$. Then, we can use the following formula:
<img width="275" alt="image" src="https://github.com/theochem/ModelHamiltonian/assets/36164007/1fef5234-6025-48ba-81cc-6c80ea57d3ab">
