### ISSUE TITLE
CleanUp Rauk module

### ISSUE THREAD

**Issue by RichRick1** [theochem/ModelHamiltonian#117]
## Description

There are few improvement that can be done to the Rauk’s dictionary module

- [x]  Move [[this code block](https://github.com/theochem/ModelHamiltonian/blob/41985d33b0f5c9c5c1a9cfcf72eb3989e164a519/moha/api.py#L46C8-L54C44)](https://github.com/theochem/ModelHamiltonian/blob/41985d33b0f5c9c5c1a9cfcf72eb3989e164a519/moha/api.py#L46C8-L54C44) into stand-alone function inside [`[utils.py](http://rauk.utils.py/)`](http://rauk.utils.py) file in `rauk` module. Call it `get_n_sites(connectivity)`. In this file should also go `get_atom_types` function from the `utils.py`  file inside the `moha` module. This function can be used to implement functionality below.
- [x]  Remove dependency on `atom_types` and `n_sites` parameters. This can be done by iterating over the connectivity instead of `atom_types` in [[this block](https://github.com/theochem/ModelHamiltonian/blob/41985d33b0f5c9c5c1a9cfcf72eb3989e164a519/moha/rauk/rauk.py#L120-L123)](https://github.com/theochem/ModelHamiltonian/blob/41985d33b0f5c9c5c1a9cfcf72eb3989e164a519/moha/rauk/rauk.py#L120-L123).
- [x]  Remove dependency on `n_sites`  from `build_one_body`  parameters. This can be done by computing parameter `n_sites` inside the function.

**Comment by giovanni-br** [comment]
I've cleaned the discussed points and I've changed the docstring a function that was clearly wrong.
