### ISSUE TITLE
Activate pre-commit on GitHub

### ISSUE THREAD

**Issue by tovrstra** [theochem/ModelHamiltonian#124]
We currently have pre-commit.ci only activated on a selection of repositories. Would you like ModelHamiltonian to be included in that list?

@PaulWAyers We may just activate it for all repositories, but I'm not sure if that is desirable?

**Comment by PaulWAyers** [comment]
I seem to recall that there was an issue having it activated for everything, perhaps the data repository was problematic. I think that @RichRick1 or @marco-2023 would remember. 

@RichRick1 can at least tell if it should be activated on this one. I am fine having it activated everywhere (as long as it doesn't break things) as I prefer having a universal QC-Devs workflow/environment.

**Comment by PaulWAyers** [comment]
Yes, I remembered correctly. pre-commit doesn't work for the `atomdb` database repository.
    https://github.com/theochem/AtomDBdata/issues/8
I think it probably works for other repositories OK.

**Comment by tovrstra** [comment]
Oh, yes, I remember. I'll take care of it.

**Comment by RichRick1** [comment]
@tovrstra we have pre-commit yaml file in the repo. Contributors still need to install pre-commit using pip, but once it's done, everything is working fine

Thanks for taking care of this!

**Comment by tovrstra** [comment]
I've added this repo to the list that will get checked with [pre-commit.ci](https://pre-commit.ci/). This will be visible as an extra check in every new pull request and push to the main branch. If it doesn't show up, please, ping me.
