### ISSUE TITLE
Testing Problems

### ISSUE THREAD

**Issue by RichRick1** [theochem/ModelHamiltonian#15]
So far there are implemented (not int the best way):

1. PPP Hamiltonian (superclass) 
2. Hubbard Hamiltonian (child class)
3. Huckel Hamiltonian (child class)
 
The main method is `get_hamilton` which returns zero, one and two body integrals as Numpy arrays.

Problems appears when testing an existing code. So far, there are couple of tests. 
1. l[Two site Hubbard model](https://phas.ubc.ca/~berciu/TEACHING/PHYS502/NOTES/se.pdf) which works great and available as test_1
2. According to this paper the per-site ground-state energy at half-filling can be written as a function of U:
![](https://user-images.githubusercontent.com/36164007/144079815-f864478c-e6c5-406a-88e0-192cd5c57251.png)
The values of this expression is -1.04036865, however proposed code doesn't return this answer. 
A good idea is test the same half-filling band but with more sites.

All code is available here: https://github.com/theochem/ModelHamiltonian/blob/upd/upd/Huckel_Hamiltonian.py

**Comment by PaulWAyers** [comment]
Gerald Knizia has a code for Hubbard models.
http://www.iboview.org/bin/bethe_ansatz.20140603.tar.bz2

This program can calculate a number of (exact) ground state properties of the infinite 1D Hubbard model, at arbitrary fillings (n) and couplings strengths (U), using the Bethe Ansatz solution.
Supported are energies/site, chemical potentials, metal-insulator transitions (1-particle gaps), and on-site spin correlation functions/particle number correlation functions.

Background: The 1D Hubbard model is one of the few exactly solvable model systems for strong correlation; this program computes reference data against which new electronic structure programs can be compared.

**Comment by PaulWAyers** [comment]
The Pariser-Parr-Pople parameters are given explicitly for benzene here.
https://www.sciencedirect.com/science/article/pii/0009261488803749?via%3Dihub
See below equation 8.

**Comment by PaulWAyers** [comment]
A few other possibly useful references. This one has explicit formulations of the occupations numbers
https://aip.scitation.org/doi/10.1063/1.1425408

and this is also maybe useful
https://journals.aps.org/prb/pdf/10.1103/PhysRevB.30.4267
https://hrcak.srce.hr/file/166534
https://arxiv.org/pdf/physics/0207086.pdf
