### ISSUE TITLE
Huckel Parameters

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/ModelHamiltonian#2]
We need to be able to

- [x]  parse atom types
- [x] assign appropriate &alpha; and &beta; values based on Rauk's atom types (attached, page 94).
- [x] compute appropriate &alpha; and &beta; values using distance/overlap.
---------
### UPD:
Based on the previous discussion with @giovanni-br we can refactor the existing pull-request
Specifically we can localize the implemented functionality into the new module "Rauk":
In the module itself:

```[tasklist]
- [x] data-related array should be moved into the separate file(s). Json can be a good file format especially, that it's a part of standard python library.
- [x] move function [`assign_Huckel_parameters`](https://github.com/AnfegoB/ModelHamiltonian/blob/fcd5daa2cde640701d0b6bd02f7527ba097a1908/moha/api.py#L75) to a separate file `Rauk.py`. Input should be list of tuples and the output are atom and bond dictionaries (we may change this later)
- [x] If in the tuple (e.g [("C1", "N2", 1.5)]) the third parameter is float, then we should build one body term using the Pariser-Parr atomic dictionary. The functionality should be stored at `PariserParr.py` file
```

[Mulliken-1949-Formulas-and-numerical-tables-for-o.pdf](https://github.com/theochem/ModelHamiltonian/files/6444866/Mulliken-1949-Formulas-and-numerical-tables-for-o.pdf)
[simple-hckel-molecular-orbital-theory.pdf](https://github.com/theochem/ModelHamiltonian/files/6444835/simple-hckel-molecular-orbital-theory.pdf)

**Comment by RichRick1** [comment]
@giovanni-br the good starting point can be pull-request from last year applicant

**Comment by RichRick1** [comment]
I think we have fixed this issue
