### ISSUE TITLE
Converting basis

### ISSUE THREAD

**Issue by RichRick1** [theochem/ModelHamiltonian#22]
@gabrielasd @AYSE-GOCER so basically we are working with [this](https://github.com/theochem/ModelHamiltonian/blob/c9d19db93a9bc35f2b8cb22107cbe2615777e77c/upd/Hamiltonian.py#L35) and [this](https://github.com/theochem/ModelHamiltonian/blob/c9d19db93a9bc35f2b8cb22107cbe2615777e77c/upd/Hamiltonian.py#L46) methods. You can use [my garbage-like code](https://github.com/theochem/ModelHamiltonian/blob/c9d19db93a9bc35f2b8cb22107cbe2615777e77c/upd/Huckel_Hamiltonian.py#L6)
[This paper](https://drive.google.com/file/d/1aBO2MM1sb34xh0t46KBTZf9Nbmo1py16/view?usp=sharing) might be helpful

**Comment by gabrielasd** [comment]
@RichRick1, a few questions:

a) what convention for the ordering of the spin-orbitals are we using? Is it the one documented on these [L24](https://github.com/theochem/ModelHamiltonian/blob/130837b0f8bb2af5a848d92e0b4d0dec9675c258/moha/ppp.py#L24)-[L40](https://github.com/theochem/ModelHamiltonian/blob/130837b0f8bb2af5a848d92e0b4d0dec9675c258/moha/ppp.py#L40) form the older MoHam version?

b) Is the `integral` parameter in those functions the ones generated by this [one_body](https://github.com/theochem/ModelHamiltonian/blob/c9d19db93a9bc35f2b8cb22107cbe2615777e77c/upd/Hamiltonian.py#L13) and [two_body](https://github.com/theochem/ModelHamiltonian/blob/c9d19db93a9bc35f2b8cb22107cbe2615777e77c/upd/Hamiltonian.py#L24) methods? Are the integrals built by those last two methods already in the general QC Hamiltonian format (i.e $h_pq$ and $g_pqrs$?


Another good reference: This [notes on symmetry of the integrals](http://vergil.chemistry.gatech.edu/notes/permsymm/permsymm.html) from [David Sherill's site](http://vergil.chemistry.gatech.edu/notes/)

**Comment by RichRick1** [comment]
@gabrielasd 
a) yes, we do use notation from the documents in lines L24-L40 (it's also in agreement with the order from notes as far as I know)
b) The integral is exactly the output from this [generate_one_body](https://github.com/theochem/ModelHamiltonian/blob/c9d19db93a9bc35f2b8cb22107cbe2615777e77c/upd/Hamiltonian.py#L13) and [generate_two_body](https://github.com/theochem/ModelHamiltonian/blob/c9d19db93a9bc35f2b8cb22107cbe2615777e77c/upd/Hamiltonian.py#L24) methods. The idea is that the output of these methods is in the sparse format: regular Scipy.sparse.csr_matrix for 1 body integral and dictionary of indices/values of non zero elements for 2 body integral (just keep this in mind cuz regular numpy operations won't work). However, besides the _data_ format, it should be the general QC Hamiltonian format
Hope it helps!

**Comment by RichRick1** [comment]
1. Every Ham should have 'sym' that is defined when Ham is created.
2. User can change the output file symmetry if symmetry is lower that the initial one
3. Convert to None symmetry before saving `to_fcidump`
