### ISSUE TITLE
Set github pages to display the sphinx-doc

### ISSUE THREAD

**Issue by msricher** [theochem/ModelHamiltonian#53]
I added a sphinx-doc build to the repo. Currently, github-pages just takes the README.md from the main branch. We can change this to have it build and deploy the sphinx website to github-pages instead, and we should do this.

**Comment by msricher** [comment]
https://python.plainenglish.io/how-to-host-your-sphinx-documentation-on-github-550254f325ae

Alternatively, we can set it up to host the website on Read The Docs. @fwmeng88 you've done this before, would you be able to help us out?

**Comment by fwmeng88** [comment]
I can help either way. Once the documentation notebooks (if you have any) are finalized, I can help with this.

**Comment by msricher** [comment]
The website is connected, and sphinx-doc deployed manually. Need to add something to Github Actions to do it automatically.
