### ISSUE TITLE
Fill out setup.py to release on pip

### ISSUE THREAD

**Issue by msricher** [theochem/ModelHamiltonian#55]
[Packaging guide is here](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/)

https://github.com/theochem/ModelHamiltonian/blob/4d5d164477d02044cb113a00b948705773b64247/setup.py#L1-L21

**Comment by nwoodweb** [comment]
Hi @msricher 

My name is Nathan Wood and I wish to make contributions to QCDevs projects. I have already spoken to Dr. Ayers about possible contributions. 

I was curious about the status of this issue, as well as the API changes.

[I made some setup.py edits (not complete) on my own fork ](https://github.com/theochem/ModelHamiltonian/compare/main...nwoodweb:main)

I was also wanting to know if `pyscf` is a dependency for ModelHamiltonian, I have included a screenshot of the Demonstration.ipynb in this message. 
![pyfail](https://user-images.githubusercontent.com/60708568/170984310-53b0a0b9-8791-4d66-9a2a-064383442f27.png)

**Comment by msricher** [comment]
Hi! 

PySCF is not a dependency of the package itself, but it can work with it. It doesn't need to be included with the requirements.

The remaining API changes we want to make are, as far as I'm aware, the other Issues on this repo.

Let me know if you would like other help/guidance. @RichRick1 will also be useful.

**Comment by RichRick1** [comment]
UPD:
We need to setup file to toml file. Also, we need to support two installation types: with and with openai dependency

**Comment by RichRick1** [comment]
I think this is done, so I'm gonna close it.
