### ISSUE TITLE
PPPHamiltonian

### ISSUE THREAD

**Issue by gharib85** [theochem/ModelHamiltonian#7]
For twoelectronmatrix
both of u_matrix and v_matrix 
Used to construct it 
But v_matrix will over write u matrix 
But they must added 
So I think instead of 
two_electron_matrix[I,j]=v_ij
Must be
two_electron_matrix[I,j]+=v_ij

**Comment by PaulWAyers** [comment]
Can we talk about it tomorrow? I'm a bit confused....

**Comment by gharib85** [comment]
two_electron_matrixu= dok_matrix((2 * self.k, 2 * self.k))
two_electron_matrixv= dok_matrix((2 * self.k, 2 * self.k))

        for i in range(self.k):
            two_electron_matrixu[i, i+self.k] = u_matrix[i]
            two_electron_matrixu[i + self.k, i] = u_matrix[i]
        for i in range(self.k):
            for j in range(i, self.k):
                v_ij = v_matrix[i, j]
                two_electron_matrixv[i, j] = v_ij
                two_electron_matrixv[j, i] = v_ij

                two_electron_matrixv[i, j+self.k] = v_ij
                two_electron_matrixv[j+self.k, i] = v_ij

                two_electron_matrixv[i+self.k, j] = v_ij
                two_electron_matrixv[j, i+self.k] = v_ij

                two_electron_matrixv[i+self.k, j+self.k] = v_ij
                two_electron_matrixv[j+self.k, i+self.k] = v_ij
        return (two_electron_matrixu+two_electron_matrixv)
