### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by RichRick1** [theochem/ModelHamiltonian#83]
It would be a good idea to support input from command line.
We can do this by leveraging .toml files 
@adsrichards has already made a pull request, however all the existing models needs to be 
supported

ToDo:

- [ ] Support CLI 
- [ ] #84

**Comment by PaulWAyers** [comment]
I think I remember that [typer](https://typer.tiangolo.com/) looked good. @FarnazH has some experience doing this for ChemTools too.

**Comment by RichRick1** [comment]
I'm closing this for now
